<a href="https://colab.research.google.com/github/ThienBao224/Data_Analytics/blob/main/BOOK_Python_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# [BOOK] Python for Data Analysis

# CHAPTER 1: Preliminaries

## 1.6 Navigating This Book

### Code Examples

In [ ]:
 import numpy as np
 import pandas as pd
 pd.options.display.max_columns = 20
 pd.options.display.max_rows = 20
 pd.options.display.max_colwidth = 80
 np.set_printoptions(precision=4, suppress=True)

### Data for Examples

In [ ]:
!ls

drive  examples  sample_data  sink.txt


In [ ]:
!pwd

/content


### Import Conventions

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import statsmodels as sm

# CHAPTER 2: Python Language Basics, IPython, and Jupyter Notebooks

## 2.1 The Python Interpreter

In [ ]:
a = 5
print(a)

5


Tạo file và chạy file vừa tạo

In [ ]:
f = open(" hello_world.py", "w")
f.write("Hello World")
f.close()

f = open(" hello_world.py", "r")
text = f.read()
print(text)
f.close()

Hello World


## 2.2 IPython Basics

### Running the IPython Shell

In [ ]:
a=5
print(a)

5


Tạo mảng 1 chiều

In [ ]:
import numpy as np
from IPython.display import display

data = [np.random.standard_normal() for i in range(7)]
display(data)

[0.27152807803718393,
 0.1767750474041871,
 -0.7850020710703584,
 0.016368041260411144,
 1.2738716817171427,
 0.39861865006743286,
 0.8177397788868653]

In [ ]:
import numpy as np
data = [np.random.standard_normal() for i in range(7)]
print(data)

[-0.18627188177061774, -0.7493961247075919, -1.256290435780577, 1.5596580768180108, -0.502726093760218, 0.9254848681922595, -0.04070458645291868]


### Introspection

In [ ]:
b = [1, 2, 3]
b?
print?

In [ ]:
def add_numbers(a, b):
 """
    Add two numbers together
    Returns
    ------
    the_sum : type of arguments
    """
 return a + b

In [ ]:
add_numbers?

## 2.3 Python Language Basics

### Language Semantics

**Indentation, not braces**

In [ ]:
array = [5, 2, 9, 1, 7]
pivot = 5
less = []
greater = []

for x in array:
    if x < pivot:
        less.append(x)
    else:
        greater.append(x)

print("less:", less)
print("greater:", greater)

less: [2, 1]
greater: [5, 9, 7]


**Comments**

In [ ]:
results = []
  for line in file_handle:
  # keep the empty lines for now
  # if len(line) == 0:
  #   continue
  results.append(line.replace("foo", "bar"))

In [ ]:
print("Reached this line")  # Simple status report

Reached this line


**Variables and argument passing**

In [ ]:
a = [1, 2, 3]
b = a
display(b)

[1, 2, 3]

In [ ]:
a.append(4)
b

[1, 2, 3, 4]

In [ ]:
def append_element(some_list, element):
    some_list.append(element)
data = [1, 2, 3]
append_element(data, 4)
data

[1, 2, 3, 4]

**Dynamic references, strong typest**

In [ ]:
a = 5
print(a)
type(a)

5


int

In [ ]:
a = "foo"
print(a)
type(a)

foo


str

In [ ]:
"5" + 5

TypeError: can only concatenate str (not "int") to str

In [ ]:
a = 4.5
b = 2
# String formatting, to be visited later
print(f"a is {type(a)}, b is {type(b)}")
a / b

a is <class 'float'>, b is <class 'int'>


2.25

In [ ]:
a = 5
isinstance(a, int)

True

In [ ]:
a = 5; b = 4.5
isinstance(a, (int, float))
isinstance(b, (int, float))

True

**Attributes and methods**

In [ ]:
a = "foo"
getattr(a, "split")

<function str.split(sep=None, maxsplit=-1)>

**Duck typing**

In [ ]:
def isiterable(obj):
    try:
        iter(obj)
        return True
    except TypeError: # not iterable
        return False

In [ ]:
isiterable("a string")

True

In [ ]:
isiterable([1, 2, 3])

True

In [ ]:
isiterable(5)

False

**Imports**

In [ ]:
with open("some_module.py", "w") as f:
    f.write("""
PI = 3.14159

def f(x):
    return x + 2

def g(a, b):
    return a + b
""")


In [ ]:
 import some_module
 result = some_module.f(5)
 pi = some_module.PI

 print(result)
 print(pi)

7
3.14159


In [ ]:
from some_module import g, PI
result = g(5, PI)

print(result)

8.14159


In [ ]:
 import some_module as sm
 from some_module import PI as pi, g as gf
 r1 = sm.f(pi)
 r2 = gf(6, pi)

 print(r1)
 print(r2)

5.14159
9.14159


**Binary operators and comparisons**

In [ ]:
5 - 7

-2

In [ ]:
12 + 21.5

33.5

In [ ]:
5 <= 2

False

In [ ]:
a = [1, 2, 3]
b = a
c = list(a)
a is b

True

In [ ]:
a is not c

True

In [ ]:
a == c

True

In [ ]:
a = None
a is None

True

**Mutable and immutable objects**

In [ ]:
a_list = ["foo", 2, [4, 5]]
a_list[2] = (3, 4)
a_list

['foo', 2, (3, 4)]

Chạy thất bại

In [ ]:
a_tuple = (3, 5, (4, 5))
a_tuple[1] = "four"

TypeError: 'tuple' object does not support item assignment

### Scalar Types

**Numeric types**

In [ ]:
ival = 17239871
ival ** 6

26254519291092456596965462913230729701102721

In [ ]:
fval = 7.243
print(f'{fval}, data type = {type(fval)}')
fval2 = 6.78e-5
print(f'{fval2}, data type = {type(fval2)}')

7.243, data type = <class 'float'>
6.78e-05, data type = <class 'float'>


Chia bình thường

In [ ]:
3 / 2

1.5

Chia lấy phần nguyên

In [ ]:
3 // 2

1

**Strings**

In [ ]:
a = 'one way of writing a string'
print(f'{a}, data type = {type(a)}')
b = "another way"
print(f'{b}, data type = {type(b)}')

one way of writing a string, data type = <class 'str'>
another way, data type = <class 'str'>


Viết 1 đoạn văn

In [ ]:
c = """
This is a longer string that
spans multiple lines
"""
print(f'{c}, data type = {type(c)}')


This is a longer string that
spans multiple lines
, data type = <class 'str'>


Đếm số dòng

In [ ]:
c.count("\n")

3

Lỗi

In [ ]:
a = "this is a string"
a[10] = "f"

TypeError: 'str' object does not support item assignment

Nối chuỗi

In [ ]:
b = a.replace("string", "longer string")
b

'this is a longer string'

In [ ]:
a

'this is a string'

Đổi kiểu dữ liệu

In [ ]:
a = 5.6
print(f'{a}, data type = {type(a)}')
s = str(a)
print(f'{s}, data type = {type(s)}')

5.6, data type = <class 'float'>
5.6, data type = <class 'str'>


Lấy 3 ký tự đầu tiên trong chuỗi

In [ ]:
s = "python"
list(s)
s[:3]

'pyt'

In [ ]:
s = "12\\34"
print(s)

12\34


In [ ]:
s = r"this\has\no\special\characters"
s

'this\\has\\no\\special\\characters'

Nối chuỗi

In [ ]:
a = "this is the first half "
b = "and this is the second half"
a + b

'this is the first half and this is the second half'

Ở đây:

{0:.2f} → lấy đối số đầu tiên, định dạng float với 2 chữ số thập phân.

{1:s} → lấy đối số thứ hai, định dạng string.

{2:d} → lấy đối số thứ ba, định dạng integer (số nguyên).

In [ ]:
template = "{0:.2f} {1:s} are worth US${2:d}"
print(f'{template}, data type = {type(template)}')

{0:.2f} {1:s} are worth US${2:d}, data type = <class 'str'>


Kết quả

In [ ]:
template.format(88.46, "Argentine Pesos", 1)

'88.46 Argentine Pesos are worth US$1'

Gán giá trị

In [ ]:
amount = 10
rate = 88.46
currency = "Pesos"
result = f"{amount} {currency} is worth US${amount / rate}"

Kết quả

In [ ]:
f"{amount} {currency} is worth US${amount / rate:.2f}"

'10 Pesos is worth US$0.11'

**Bytes and Unicode**

Thêm dấu

In [ ]:
val = "español"
print(f'{val}, data type = {type(val)}')

español, data type = <class 'str'>


Chuyển chuỗi val (str) thành bytes theo chuẩn UTF-8.

In [ ]:
val_utf8 = val.encode("utf-8")
val_utf8
type(val_utf8)

bytes

In [ ]:
val_utf8.decode("utf-8")

'español'

In [ ]:
val.encode("latin1")
val.encode("utf-16")
val.encode("utf-16le")

b'e\x00s\x00p\x00a\x00\xf1\x00o\x00l\x00'

**Booleans**

In [ ]:
True and True

True

In [ ]:
False or True

True

In [ ]:
int(False)

0

In [ ]:
int(True)

1

In [ ]:
a = True
b = False
not a

False

In [ ]:
not b

True

**Type casting**

In [ ]:
s = "3.14159"
fval = float(s)
type(fval)

float

In [ ]:
int(fval)

3

In [ ]:
bool(fval)

True

In [ ]:
bool(0)

False

**None**

None là kiểu giá trị null của Python

In [ ]:
a = None
a is None

True

In [ ]:
b = 5
b is not None

True

None là giá trị mặc định chung cho các đối số hàm

In [ ]:
def add_and_maybe_multiply(a, b, c=None):
  result = a + b
  if c is not None:
    result = result * c
  return result


print(add_and_maybe_multiply(2, 3))       # chỉ cộng a + b
print(add_and_maybe_multiply(2, 3, 4))    # cộng rồi nhân với c

5
20


**Dates and times**

Tạo 1 đối tượng datetime

In [ ]:
from datetime import datetime, date, time
dt = datetime(2011, 10, 29, 20, 30, 21)

Lấy ra ngày

In [ ]:
dt.day

29

Lấy ra phút

In [ ]:
dt.minute

30

Lấy ra ngày tháng

In [ ]:
dt.date()

datetime.date(2011, 10, 29)

Lấy ra thời gian

In [ ]:
dt.time()

2011-10-29 20:30:21, data type = <class 'datetime.datetime'>


chuyển đối tượng datetime thành chuỗi (str)

In [ ]:
dt.strftime("%Y-%m-%d %H:%M")

'2011-10-29 20:30'

Tách ra theo dạng Year Month Days

In [ ]:
datetime.strptime("20091031", "%Y%m%d")

datetime.datetime(2009, 10, 31, 0, 0)

Chỉ lấy giờ còn phút, giây = 0

In [ ]:
dt_hour = dt.replace(minute=0, second=0)
dt_hour

datetime.datetime(2011, 10, 29, 20, 0)

Giá trị ban đầu

In [ ]:
dt

datetime.datetime(2011, 10, 29, 20, 30, 21)

In [ ]:
dt2 = datetime(2011, 11, 15, 22, 30)
delta = dt2 - dt


In [ ]:
display(delta)

datetime.timedelta(days=17, seconds=7179)

In [ ]:
type(delta)

datetime.timedelta

In [ ]:
dt

datetime.datetime(2011, 10, 29, 20, 30, 21)

In [ ]:
dt + delta

datetime.datetime(2011, 11, 15, 22, 30)

### Control Flow

**if, elif, and else**

In [ ]:
x = -5
if x < 0:
  print("It's negative")

It's negative


In [ ]:
if x < 0:
  print("It's negative")
elif x == 0:
  print("Equal to zero")
elif 0 < x < 5:
  print("Positive but smaller than 5")
else:
  print("Positive and larger than or equal to 5")

It's negative


In [ ]:
a = 5; b = 7
c = 8; d = 4
if a < b or c > d:
  print("Made it")

Made it


In [ ]:
4 > 3 > 2 > 1

True

**for loops**

In [ ]:
sequence = [1, 2, None, 4, None, 5]
total = 0
for value in sequence:
  if value is None:
    continue
  total += value
print(total)

12


In [ ]:
sequence = [1, 2, 0, 4, 6, 5, 2, 1]
total_until_5 = 0
for value in sequence:
    if value == 5:
      break
    total_until_5 += value
    print(total_until_5)

1
3
3
7
13


In [ ]:
for i in range(4):
    for j in range(4):
        if j > i:
            break
        print((i, j))

(0, 0)
(1, 0)
(1, 1)
(2, 0)
(2, 1)
(2, 2)
(3, 0)
(3, 1)
(3, 2)
(3, 3)


**while loops**

In [ ]:
x = 256
total = 0
while x > 0:
  if total > 500:
    break
  total += x
  x = x // 2

print(total)

504


**pass**

In [ ]:
if x < 0:
  print("negative!")
elif x == 0:
  # TODO: put something smart here
  pass
else:
  print("positive!")

positive!


**range**

Tạo một đối tượng range từ 0 đến 9

In [ ]:
range(10)

range(0, 10)

Tạo một danh sách các số nguyên từ 0 đến 9.

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Tạo một danh sách các số nguyên từ 0 đến 20 và chỉ lấy số chẵn

In [ ]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [ ]:
list(range(5, 0, -1))

[5, 4, 3, 2, 1]

In [ ]:
seq = [1, 2, 3, 4]
for i in range(len(seq)):
    print(f"element {i}: {seq[i]}")

element 0: 1
element 1: 2
element 2: 3
element 3: 4


In [ ]:
total = 0
for i in range(100_000):
    # % is the modulo operator
    if i % 3 == 0 or i % 5 == 0:
        total += i
print(total)

2333316668


# CHAPTER 3: Built-In Data Structures Functions, and Files

## 3.1 Data Structures and Sequences

### Tuple

Cách khai báo

In [ ]:
tup = (4, 5, 6)
tup

(4, 5, 6)

In [ ]:
tup = 4, 5, 6
tup

(4, 5, 6)

Chuyển chuỗi thành ký tự

In [ ]:
tuple([4, 0, 2])
tup = tuple('string')
tup

('s', 't', 'r', 'i', 'n', 'g')

Vị trí đầu

In [ ]:
tup[0]

's'

Tạo tuple lồng nhau

In [ ]:
nested_tup = (4, 5, 6), (7, 8)
nested_tup

((4, 5, 6), (7, 8))

Lấy phần tử đầu tiên của nested_tup

In [ ]:
nested_tup[0]

(4, 5, 6)

Lấy phần tử tiếp theo của nested_tup

In [ ]:
nested_tup[1]

(7, 8)

không thể gán lại phần tử trực tiếp phải thông qua append

In [ ]:
tup = tuple(['foo', [1, 2], True])
tup[2] = False

TypeError: 'tuple' object does not support item assignment

Gán thành công 3 vào mảng

In [ ]:
tup[1].append(3)
tup

('foo', [1, 2, 3], True)

Tuple đc nối theo thứ tự từ trái sang phải.

In [ ]:
(4, None, 'foo') + (6, 0) + ('bar',)

(4, None, 'foo', 6, 0, 'bar')

Lặp lại 4 lần

In [ ]:
('foo', 'bar') * 4

('foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'bar')

**Unpacking tuples**

Gán lần lượt các phần tử của tuple

In [ ]:
tup = (4, 5, 6)
a, b, c = tup
b

5

In [ ]:
tup = 4, 5, (6, 7)
a, b, (c, d) = tup
d

7

In [ ]:
a, b = 1, 2
a

1

In [ ]:
b


2

In [ ]:
b, a = a, b
a

2

In [ ]:
b

2

Vòng lặp for với tuple

In [ ]:
seq = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
for a, b, c in seq:
    print(f'a={a}, b={b}, c={c}')

a=1, b=2, c=3
a=4, b=5, c=6
a=7, b=8, c=9


a, b, *rest = values  
Gán lần lượt:
*   a = 1
*   b = 2
*   rest = [3, 4, 5] (rest luôn tạo một list chứa các phần tử còn lại.)

In [ ]:
values = 1, 2, 3, 4, 5
a, b, *rest = values

In [ ]:
a

1

In [ ]:
b

2

In [ ]:
rest

[3, 4, 5]

_ (thường dùng để bỏ qua giá trị không cần thiết)

In [ ]:
a, b, *_ = values
print(a)
print(b)
print(_)

1
2
[3, 4, 5]


**Tuple methods**

Đếm số 2 trong tuple

In [ ]:
a = (1, 2, 2, 2, 3, 4, 2)
a.count(2)

4

### List

Chuyển tuple thành list

In [ ]:
a_list = [2, 3, 7, None]
tup = ("foo", "bar", "baz")
b_list = list(tup)
b_list

['foo', 'bar', 'baz']

Thay vị trí [1]

In [ ]:
b_list[1] = "peekaboo"
b_list

['foo', 'peekaboo', 'baz']

Tạo một đối tượng range

In [ ]:
gen = range(10)
gen

range(0, 10)

Chuyển range thành list

In [ ]:
list(gen)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

**Adding and removing elements**

Thêm phần tử vào cuối list

In [ ]:
b_list.append("dwarf")
b_list

['foo', 'peekaboo', 'baz', 'dwarf']

Thêm phần tử vào vị trí thứ 2 trong list

In [ ]:
b_list.insert(1, "red")
b_list

['foo', 'red', 'peekaboo', 'baz', 'dwarf']

Xóa phần tử thứ 3

In [ ]:
b_list.pop(2)


'peekaboo'

In [ ]:
b_list

['foo', 'red', 'baz', 'dwarf']

Thêm phần tử foo vào cuối list

In [ ]:
b_list.append("foo")
b_list

['foo', 'red', 'baz', 'dwarf', 'foo']

Xoá phần tử foo đầu tiên

In [ ]:
b_list.remove("foo")
b_list

['red', 'baz', 'dwarf', 'foo']

Kiểm tra xem phần tử có trong chuỗi k

In [ ]:

"dwarf" in b_list

True

In [ ]:
"dwarf" not in b_list

False

**Concatenating and combining lists**

Nối hai list lại với nhau.

In [ ]:
[4, None, "foo"] + [7, 8, (2, 3)]

[4, None, 'foo', 7, 8, (2, 3)]

In [ ]:
x = [4, None, "foo"]
x.extend([7, 8, (2, 3)])
x

[4, None, 'foo', 7, 8, (2, 3)]

Gom tất cả phần tử từ nhiều list con vào một list duy nhất

In [ ]:
list_of_lists = [[1, 2], [5]]
everything = [ [3, 4]]
for chunk in list_of_lists:
    everything.extend(chunk)

print(everything)

[[3, 4], 1, 2, 5]


In [ ]:
everything = [ [7, 8]]
for chunk in list_of_lists:
  everything = everything + chunk

print(everything)

[[7, 8], 1, 2, 5]


**Sorting**

Sắp xếp list theo thứ tự tắng dần

In [ ]:
a = [7, 2, 5, 1, 3]
a.sort()
a

[1, 2, 3, 5, 7]

Sắp xếp list theo độ dài các từ, từ ngắn đến dài.

In [ ]:
b = ["saw", "small", "He", "foxes", "six"]
b.sort(key=len)
b

['He', 'saw', 'six', 'small', 'foxes']

**Slicing**

Lấy các phần tử từ index 1 đến index 4

In [ ]:
seq = [7, 2, 3, 7, 5, 6, 0, 1]
seq[1:5]

[2, 3, 7, 5]

Căt từ index 3 đến 4 (7, 5)

In [ ]:
seq[3:5] = [6, 3]
seq

[7, 2, 3, 6, 3, 6, 0, 1]

Lấy 5 phần tử đầu tiên (index 0 đến 4).

In [ ]:
seq[:5]

[7, 2, 3, 6, 3]

Lấy tất cả phần tử từ index 3 trở đi.

In [ ]:
seq[3:]

[6, 3, 6, 0, 1]

Lấy 4 phần tử cuối cùng

In [ ]:
seq[-4:]

[3, 6, 0, 1]

Lấy 4 phần tử bắt đầu từ index -6 đến trước index -2.

In [ ]:
seq[-6:-2]

[3, 6, 3, 6]

In [ ]:
seq[::2]

[7, 3, 3, 0]

In [ ]:

seq[::-1]

[1, 0, 6, 3, 6, 3, 2, 7]

### Dictionary

In [ ]:
empty_dict = {}
d1 = {"a": "some value", "b": [1, 2, 3, 4]}
d1

{'a': 'some value', 'b': [1, 2, 3, 4]}

In [ ]:
d1[7] = "an integer"
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [ ]:
d1["b"]

[1, 2, 3, 4]

In [ ]:
"b" in d1

True

In [ ]:
d1[5] = "some value"
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer', 5: 'some value'}

In [ ]:
d1["dummy"] = "another value"
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 5: 'some value',
 'dummy': 'another value'}

In [ ]:
del d1[5]
d1

{'a': 'some value',
 'b': [1, 2, 3, 4],
 7: 'an integer',
 'dummy': 'another value'}

In [ ]:
ret = d1.pop("dummy")
ret

'another value'

In [ ]:
d1

{'a': 'some value', 'b': [1, 2, 3, 4], 7: 'an integer'}

In [ ]:
list(d1.keys())

['a', 'b', 7]

In [ ]:
list(d1.values())

['some value', [1, 2, 3, 4], 'an integer']

In [ ]:
list(d1.items())

[('a', 'some value'), ('b', [1, 2, 3, 4]), (7, 'an integer')]

In [ ]:
d1.update({"b": "foo", "c": 12})
d1

{'a': 'some value', 'b': 'foo', 7: 'an integer', 'c': 12}

**Creating dictionaries from sequences**

In [ ]:
key_list = ['a', 'b', 'c']
value_list = [1, 2, 3]

mapping = {}
for key, value in zip(key_list, value_list):
    mapping[key] = value

print(mapping)

{'a': 1, 'b': 2, 'c': 3}


In [ ]:
tuples = zip(range(5), reversed(range(5)))
tuples

In [ ]:
mapping = dict(tuples)
mapping

{0: 4, 1: 3, 2: 2, 3: 1, 4: 0}

**Default values**

In [ ]:
words = ["apple", "bat", "bar", "atom", "book"]
by_letter = {}

for word in words:
    letter = word[0]
    if letter not in by_letter:
        by_letter[letter] = [word]
    else:
        by_letter[letter].append(word)

by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [ ]:
by_letter = {}
for word in words:
    letter = word[0]
    by_letter.setdefault(letter, []).append(word)
by_letter

{'a': ['apple', 'atom'], 'b': ['bat', 'bar', 'book']}

In [ ]:
from collections import defaultdict
by_letter = defaultdict(list)
for word in words:
    by_letter[word[0]].append(word)

**Valid dictionary key types**

Chỉ nhận các đối tượng không thay đổi còn list là mutable

In [ ]:
hash("string")
hash((1, 2, (2, 3)))
hash((1, 2, [2, 3])) # fails because lists are mutable

TypeError: unhashable type: 'list'

In [ ]:
d = {}
d[tuple([1, 2, 3])] = 5
d

{(1, 2, 3): 5}

**Set**

In [ ]:
set([2, 2, 2, 1, 3, 3])

{1, 2, 3}

In [ ]:
{2, 2, 2, 1, 3, 3}

{1, 2, 3}

Truyền giá trị cho a,b

In [ ]:
a = {1, 2, 3, 4, 5}
b = {3, 4, 5, 6, 7, 8}

In [ ]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
a | b

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
a.intersection(b)

{3, 4, 5}

In [ ]:
a & b

{3, 4, 5}

In [ ]:
c = a.copy()
c |= b
c

{1, 2, 3, 4, 5, 6, 7, 8}

In [ ]:
d = a.copy()
d &= b
d

{3, 4, 5}

In [ ]:
my_data = [1, 2, 3, 4]
my_set = {tuple(my_data)}
my_set

{(1, 2, 3, 4)}

In [ ]:
a_set = {1, 2, 3, 4, 5}
{1, 2, 3}.issubset(a_set)

True

In [ ]:
a_set.issuperset({1, 2, 3})

True

In [ ]:
{1, 2, 3} == {3, 2, 1}

True

### Built-In Sequence Functions

**sorted**

In [ ]:
sorted([7, 1, 2, 6, 0, 3, 2])

[0, 1, 2, 2, 3, 6, 7]

In [ ]:
sorted("horse race")

[' ', 'a', 'c', 'e', 'e', 'h', 'o', 'r', 'r', 's']

**zip**

In [ ]:
seq1 = ["foo", "bar", "baz"]
seq2 = ["one", "two", "three"]
zipped = zip(seq1, seq2)
list(zipped)

[('foo', 'one'), ('bar', 'two'), ('baz', 'three')]

In [ ]:
seq3 = [False, True]
list(zip(seq1, seq2, seq3))

[('foo', 'one', False), ('bar', 'two', True)]

In [ ]:
for index, (a, b) in enumerate(zip(seq1, seq2)):
    print(f"{index}: {a}, {b}")

0: foo, one
1: bar, two
2: baz, three


**reversed**

In [ ]:
list(reversed(range(10)))

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

### List, Set, and Dictionary Comprehensions

In [ ]:
strings = ["a", "as", "bat", "car", "dove", "python"]
[x.upper() for x in strings if len(x) > 2]

['BAT', 'CAR', 'DOVE', 'PYTHON']

In [ ]:
unique_lengths = {len(x) for x in strings}
unique_lengths

{1, 2, 3, 4, 6}

In [ ]:
set(map(len, strings))

{1, 2, 3, 4, 6}

In [ ]:
loc_mapping = {value: index for index, value in enumerate(strings)}
loc_mapping

{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

**Nested list comprehensions**

In [ ]:
all_data = [["John", "Emily", "Michael", "Mary", "Steven"],
            ["Maria", "Juan", "Javier", "Natalia", "Pilar"]]

In [ ]:
names_of_interest = []
for names in all_data:
    enough_as = [name for name in names if name.count("a") >= 2]
    names_of_interest.extend(enough_as)
names_of_interest

['Maria', 'Natalia']

In [ ]:
result = [name for names in all_data for name in names
          if name.count("a") >= 2]
result

['Maria', 'Natalia']

In [ ]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
flattened

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
flattened = []

for tup in some_tuples:
    for x in tup:
        flattened.append(x)

In [ ]:
[[x for x in tup] for tup in some_tuples]

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## 3.2 Functions

Tạo function

In [ ]:
def my_function(x, y):
    return x + y

In [ ]:
my_function(1, 2)

3

In [ ]:
result = my_function(1, 2)
result

3

In [ ]:
def function_without_return(x):
    print(x)

result = function_without_return("hello!")
print(result)

hello!
None


In [ ]:
def my_function2(x, y, z=1.5):
    if z > 1:
        return z * (x + y)
    else:
        return z / (x + y)

In [ ]:
my_function2(5, 6, z=0.7)

0.06363636363636363

In [ ]:
my_function2(3.14, 7, 3.5)

35.49

In [ ]:
my_function2(10, 20)

45.0

**Namespaces, Scope, and Local Functions**

In [ ]:
def func():
  a = []
  for i in range(5):
    a.append(i)

In [ ]:
a = []
def func():
    for i in range(5):
        a.append(i)

In [ ]:
func()
a

[0, 1, 2, 3, 4]

In [ ]:
func()
a

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [ ]:
a = None
def bind_a_variable():
    global a
    a = []
bind_a_variable()
print(a)

[]


### Returning Multiple Values

In [ ]:
def f():
  a = 5
  b = 6
  c = 7
  return a, b, c

In [ ]:
a, b, c = f()

In [ ]:
return_value = f()

In [ ]:
print(return_value)

(5, 6, 7)


In [ ]:
def f():
  a = 5
  b = 6
  c = 7
  return {"a" : a, "b" : b, "c" : c}

### Functions Are Objects

In [ ]:
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
          "south   carolina##", "West virginia?"]

In [ ]:
import re

def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub("[!#?]", "", value)
        value = value.title()
        result.append(value)
    return result

In [ ]:

clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [ ]:
def remove_punctuation(value):
    return re.sub("[!#?]", "", value)

clean_ops = [str.strip, remove_punctuation, str.title]

def clean_strings(strings, ops):
    result = []
    for value in strings:
        for func in ops:
            value = func(value)
        result.append(value)
    return result

In [ ]:
clean_strings(states, clean_ops)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [ ]:
for x in map(remove_punctuation, states):
    print(x)

   Alabama 
Georgia
Georgia
georgia
FlOrIda
south   carolina
West virginia


### Anonymous (Lambda) Functions

In [ ]:
def short_function(x):
    return x * 2

equiv_anon = lambda x: x * 2

In [ ]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints = [4, 0, 1, 5, 6]
apply_to_list(ints, lambda x: x * 2)

[8, 0, 2, 10, 12]

In [ ]:
strings = ["foo", "card", "bar", "aaaa", "abab"]

In [ ]:
strings.sort(key=lambda x: len(set(x)))
strings

['aaaa', 'foo', 'abab', 'bar', 'card']

### Generators

In [ ]:
some_dict = {"a": 1, "b": 2, "c": 3}
for key in some_dict:
    print(key)

a
b
c


In [ ]:
dict_iterator = iter(some_dict)
dict_iterator

In [ ]:
list(dict_iterator)

[]

In [ ]:
def squares(n=10):
    print(f"Generating squares from 1 to {n ** 2}")
    for i in range(1, n + 1):
        yield i ** 2

In [ ]:
gen = squares()
gen

<generator object squares at 0x7a0230177d80>

In [ ]:
for x in gen:
    print(x, end=" ")

Generating squares from 1 to 100
1 4 9 16 25 36 49 64 81 100 

**Generator expressions**

In [ ]:
gen = (x ** 2 for x in range(100))
gen

<generator object <genexpr> at 0x7a02303ffed0>

In [ ]:
def _make_gen():
  for x in range(100):
    yield x ** 2
gen = _make_gen()

In [ ]:
sum(x ** 2 for x in range(100))

328350

In [ ]:
dict((i, i ** 2) for i in range(5))

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16}

**itertools module**

In [ ]:
import itertools
def first_letter(x):
    return x[0]

names = ["Alan", "Adam", "Wes", "Will", "Albert", "Steven"]

for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names)) # names is a generator

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


### Errors and Exception Handling

In [ ]:
float("1.2345")

1.2345

Không phải chuỗi biểu diễn số hợp lệ.

In [ ]:
float("something")

ValueError: could not convert string to float: 'something'

Hàm chuyển sang float

In [ ]:
def attempt_float(x):
    try:
        return float(x)
    except:
        return x

In [ ]:
attempt_float("1.2345")

1.2345

In [ ]:
attempt_float("something")

'something'

Lỗi xảy ra vì (1, 2) là tuple, không phải số hay chuỗi số hợp lệ.

In [ ]:
float((1, 2))

TypeError: float() argument must be a string or a real number, not 'tuple'

Hàm chuyển sang float

In [ ]:
def attempt_float(x):
    try:
        return float(x)
    except ValueError:
        return x

In [ ]:
attempt_float((1, 2))

TypeError: float() argument must be a string or a real number, not 'tuple'

In [ ]:
def attempt_float(x):
    try:
        return float(x)
    except (TypeError, ValueError):
        return x

In [ ]:
path = "examples/segismundo.txt"

def write_to_file(f):
    f.write("Đây là nội dung ví dụ.\n")
    f.write("Thêm dòng nữa.")

f = open(path, mode="w", encoding="utf-8")
try:
    write_to_file(f)
finally:
    f.close()

In [ ]:
 f = open(path, mode="w")
 try:
  write_to_file(f)
 except:
  print("Failed")
 else:
  print("Succeeded")
 finally:
  f.close()

Succeeded


### 3.3 Files and the Operating System

In [ ]:
import os
os.makedirs("examples", exist_ok=True)

file_path = "examples/segismundo.txt"
with open(file_path, "w", encoding="utf-8") as f:
    f.write("Đây là nội dung\n")

with open(file_path, "r", encoding="utf-8") as f:
    print(f.read())

Đây là nội dung



In [ ]:
path = "examples/segismundo.txt"
f = open(path, encoding="utf-8")

In [ ]:

lines = [x.rstrip() for x in open(path, encoding="utf-8")]
lines

['Đây là nội dung ví dụ.', 'Thêm dòng nữa.']

In [ ]:
f.close()

In [ ]:
with open(path, encoding="utf-8") as f:
    lines = [x.rstrip() for x in f]

In [ ]:
f1 = open(path)
f1.read(10)

'Đây là nội'

In [ ]:
f2 = open(path, mode="rb")  # Binary mode
f2.read(10)

b'\xc4\x90\xc3\xa2y l\xc3\xa0 '

In [ ]:
f1.tell()

15

In [ ]:
f2.tell()

10

In [ ]:
import sys
sys.getdefaultencoding()

'utf-8'

In [ ]:
f1.seek(3)

3

In [ ]:
f1.read(1)

''

In [ ]:
f1.tell()

49

In [ ]:
f1.close()
f2.close()

In [ ]:
path

with open("tmp.txt", mode="w") as handle:
    handle.writelines(x for x in open(path) if len(x) > 1)

with open("tmp.txt") as f:
    lines = f.readlines()

lines

['Đây là nội dung ví dụ.\n', 'Thêm dòng nữa.']

In [ ]:
import os
os.remove("tmp.txt")

In [ ]:
with open(path) as f:
    chars = f.read(10)
chars

'Đây là nội'

In [ ]:
len(chars)

10

In [ ]:
with open(path, mode="rb") as f:
    data = f.read(10)
data

b'\xc4\x90\xc3\xa2y l\xc3\xa0 '

In [ ]:
data.decode("utf-8")

'Đây là '

In [ ]:
data[:4].decode("utf-8")

'Đâ'

In [ ]:
source_path = "examples/segismundo.txt"
sink_path = "sink.txt"

with open(path, encoding="utf-8") as source:
    with open(sink_path, "w", encoding="utf-8") as sink:
        sink.write(source.read())

with open(sink_path, encoding="utf-8") as f:
    print(f.read(10))

Đây là nội


In [ ]:
f = open(path, encoding='utf-8')

In [ ]:
f.read(5)

'Đây l'

In [ ]:
f.seek(4)

4

In [ ]:
f.read(1)

'y'

In [ ]:
f.close()

# CHAPTER 4: NumPy Basics: Arrays andVectorized Computation

In [ ]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [ ]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

In [ ]:
%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

1.05 ms ± 94.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
65.7 ms ± 13.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## 4.1 The NumPy ndarray: A Multidimensional Array Object

Tạo mảng trong Numpy

In [ ]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

Nhân mảng cho 10


In [ ]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

Cộng thêm chính nó

In [ ]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

Mô tả kích thước của mảng

In [ ]:
data.shape

(2, 3)

Kiểu dữ liệu mảng

In [ ]:
data.dtype

dtype('float64')

### Creating ndarrays

Tạo mảng 1 chiều

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Tạo mảng 2 chiều

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

Số chiều của mảng

In [ ]:
arr2.ndim

2

Kích thước mảng

In [ ]:
arr2.shape

(2, 4)

Kiểu dữ liệu mảng

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int64')

Tạo mảng 1 chiều có giá trị bằng 0

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Tạo mảng 2 chiều có giá trị bằng 0

In [ ]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Tạo mảng đúng kích thước nhưng giá trị bên trong chưa xác định

In [ ]:
np.empty((2, 3, 2))

array([[[6.7336e-310, 6.7336e-310],
        [0.0000e+000, 0.0000e+000],
        [0.0000e+000, 1.5001e+248]],

       [[4.3117e-096, 1.1600e-028],
        [3.7778e+180, 1.1600e-028],
        [4.1946e+228, 1.5554e+161]]])

Tạo mảng có n phần tử

In [ ]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### Data Types for ndarrays

Kiểu dữ liệu của mảng

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('float64')

In [ ]:
arr2.dtype

dtype('int32')

Tạo mảng và xem kiểu dữ liệu mặc định

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

Ép kiểu dữ liệu vào

In [ ]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [ ]:
float_arr.dtype

dtype('float64')

Ép kiểu dữ liệu khác vào

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [ ]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=str)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

### Arithmetic with NumPy Arrays

Tạo mảng arr

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

Nhân phân tử trong mảng

In [ ]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Trừ phần tử trong mảng

In [ ]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

Chia phần tử trong mảng

In [ ]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

Nhân phần tử trong mảng với 2

In [ ]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Tạo mảng arr2

In [ ]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

So sánh mảng arr2 và arr nếu đúng True

In [ ]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Basic Indexing and Slicing

Tạo mảng gồm 10 phần tử

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Lấy phần tử vị trí thứ 6

In [ ]:
arr[5]

np.int64(5)

Cắt mảng từ vị trí 5-8

In [ ]:
arr[5:8]


array([5, 6, 7])

Thay giá trị từ khoảng đó

In [ ]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Gán phần mảng đã cắt

In [ ]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

Gán số vào vị trí thứ 2

In [ ]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

Gán số vào cả mảng

In [ ]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Tạo mảng arr2d

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

Giá trị của hàng 0 cột 2

In [ ]:
arr2d[0][2]

np.int64(3)

In [ ]:
arr2d[0, 2]

np.int64(3)

Tạo mảng arr3d

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Lấy khối đầu tiên

In [ ]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Thay giá trị của khối đầu

In [ ]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Trả về giá trị cũ

In [ ]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Giá trị khối 1 hàng 0

In [ ]:
arr3d[1, 0]

array([7, 8, 9])

Lấy khối 1 ra

In [ ]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

Giá trị hàng 1

In [ ]:
x[0]

array([7, 8, 9])

**Indexing with slices**

In [ ]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

Cắt khoảng 1 tới 6

In [ ]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Lấy 2 hàng

In [ ]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

Lấy từ hàng 0 cột 1 trở đi

In [ ]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
lower_dim_slice = arr2d[1, :2]

Mảng 1 chiều

In [ ]:
lower_dim_slice.shape

(2,)

Lấy 2 hàng đầu của cột 2

In [ ]:
arr2d[:2, 2]

array([3, 6])

Lấy cột 0

In [ ]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [ ]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

### Boolean Indexing

In [ ]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [ ]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

Kiếm Bob trong mảng

In [ ]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [ ]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [ ]:
data[names == "Bob", 1:]

array([[7],
       [0]])

In [ ]:
data[names == "Bob", 1]

array([7, 0])

In [ ]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
~(names == "Bob")

array([False,  True,  True, False,  True,  True,  True])

In [ ]:
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [ ]:
mask = (names == "Bob") | (names == "Will")
mask

array([ True, False,  True,  True,  True, False, False])

In [ ]:
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [ ]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

# Kết thúc