<a href="https://colab.research.google.com/github/ThienBao224/Data_Analytics/blob/main/Python_Numpy_Matplotlib_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Numpy Matplotlib Pandas**

# Ngôn ngữ Python

## 1. Mở đầu

### 1.1. Giới thiệu ngôn ngữ python

### 1.2. Cách thực hiện câu lệnh, chương trình Python

Khởi chạy

In [ ]:
a=20*10
b=a+25
b

225

### 1.3. Biến, Kiểu dữ liệu, Khối lệnh

Biến

In [ ]:
n = 12 # biến n là kiểu nguyên
print(f'{n}, data type = {type(n)}')

n = n + 0.1 # biến n chuyển sang kiểu thực
print(f'{n}, data type = {type(n)}')

12, data type = <class 'int'>
12.1, data type = <class 'float'>


In [ ]:
a=100
b=1.
type(a), type(b)

(int, float)

In [ ]:
id(a), id(b)

(11645256, 137136153064752)

Dữ liệu kiểu chuỗi

In [ ]:
# chuỗi trong nó có chứa dấu nháy đơn
with_quote = "I ain't gonna"
print(with_quote)
# chuỗi có nôi dung nằm trên 2 dòng
longer = """This string has multiple lines in it"""
print(longer)

I ain't gonna
This string has multiple lines in it


Chuỗi trần

In [ ]:
a = r'\neu moi ngay' # chuoi tran, bo qua Escape Sequence \n
print (a)

\neu moi ngay


Chú thích

In [ ]:
print("Chuong trinh python") #Day la cau lenh in ra chuoi

Chuong trinh python


### 1.4. Nhập và Xuất dữ liệu

#### Xuất dữ liệu

In [ ]:
a = 3.564

print(42)

print("a = ", a)

print("a = \n", a)

print("a","b")

print("a","b",sep="")

print(192,168,178,42,sep=".")

print("a","b",sep=":-)")


42
a =  3.564
a = 
 3.564
a b
ab
192.168.178.42
a:-)b


#### Nhập dữ liệu

In [ ]:
name = input("What's your name? ")
print("Nice to meet you " + name + "!")
age = input("Your age? ")
print("You are already " + age + " years old, " + name + "!")

What's your name? Bao
Nice to meet you Bao!
Your age? 23
You are already 23 years old, Bao!


Có thể kết hợp chuyển kiểu nếu muốn tường minh

In [ ]:
age = int(input("Your age? "))
print("You are already %d years old!", age)

Your age? 22
You are already %d years old! 22


### 1.5. Ví dụ minh hoạ

Giải phương trình bậc 2

In [ ]:
#Nhập a,b,c kiểu số thực và tính delta
a = float(input("A = "))
b = float(input("B = "))
c = float(input("C = "))
delta = b*b-4*a*c

A = 2
B = 3
C = 5


In [ ]:
#Biện luận các trường hợp của delta
if delta==0:
  print("Nghiem kep: x = ", str(-b/2/a))

In [ ]:
#Các khối lệnh con được viết thụt vào so với khối cha
if delta<0:
  print("Phuong trinh vo nghiem")

Phuong trinh vo nghiem


In [ ]:
#Tính căn bậc 2 bằng phép lũy thừa 0.5
if delta>0:
  print("X1 = " + str((-b+delta**0.5)/2/a))
  print("X2 = " + str((-b-delta**0.5)/2/a))

## 2. Kiểu dữ liệu & phép toán

### 2.1. Kiểu dữ liệu và phép toán liên quan

#### Kiếu số

Python viết số nguyên theo nhiều hệ cơ số

In [50]:
A = 1234 # hệ cơ số 10
B = 0xAF1 # hệ cơ số 16
C = 0o772 # hệ cơ số 8
D = 0b1001 # hệ cơ số 2

sources = {
    "A": "1234",
    "B": "0xAF1",
    "C": "0o772",
    "D": "0b1001"
}

def detect_base(num_str):
    if num_str.startswith(("0x", "0X")):
        return 16
    elif num_str.startswith(("0o", "0O")):
        return 8
    elif num_str.startswith(("0b", "0B")):
        return 2
    else:
        return 10

# Duyệt qua các biến
for name, literal in sources.items():
    base = detect_base(literal)
    value = eval(name)   # lấy giá trị thực tế từ biến A, B, C, D
    print(f"{name} = {literal} , hệ cơ số {base}")


A = 1234 , hệ cơ số 10
B = 0xAF1 , hệ cơ số 16
C = 0o772 , hệ cơ số 8
D = 0b1001 , hệ cơ số 2


Chuyển đổi từ số nguyên thành string ở các hệ cơ
số khác nhau

In [47]:
K = str(1234) # chuyển thành str ở hệ cơ số 10
L = hex(1234) # chuyển thành str ở hệ cơ số 16
M = oct(1234) # chuyển thành str ở hệ cơ số 8
N = bin(1234) # chuyển thành str ở hệ cơ số 2
print("K (thập phân):", K)
print("L (hex):", L)
print("M (oct):", M)
print("N (bin):", N)

K (thập phân): 1234
L (hex): 0x4d2
M (oct): 0o2322
N (bin): 0b10011010010


Số thực (float) trong python có thể viết kiểu thông thường hoặc dạng khoa học

In [51]:
X = 12.34
print(f'{X}, data type = {type(X)}')
Y = 314.15279e-2 # dạng số nguyên và phần mũ 10
print(f'{Y}, data type = {type(Y)}')

12.34, data type = <class 'float'>
3.1415279, data type = <class 'float'>


In [ ]:
Python hỗ trợ kiểu số phức, với chữ j đại diện cho phần ảo

In [54]:
A = 3+4j
print(f'{A}, data type = {type(A)}')
B = 2-2j
print(f'{B}, data type = {type(B)}')
print(A+B) # sẽ in ra (5+2j)

(3+4j), data type = <class 'complex'>
(2-2j), data type = <class 'complex'>
(5+2j)


#### Phép toán

Chia đúng (/)

In [57]:
10/3 # 3.3333333333333335

3.3333333333333335

Chia nguyên (//)

In [56]:
10//3 # 3 (nhanh hơn phép /)

3

Phép kiểm tra tập

In [58]:
1 in [1, 2, 3]

True

### 2.2. Cấu trúc rẽ nhánh

Cấu trúc rẽ nhánh if-else

In [62]:
name = input("What's your name? ")
print("Nice to meet you " + name + "!")
age = int(input("Your age? "))
print("You are already", age, "years old,", name, "!")
if age>=18:
  print("Đủ tuổi đi bầu cử")
  if age>100:
    print("Có vẻ sai sai!")
else:
  print("Nhỏ quá")

What's your name? Bao
Nice to meet you Bao!
Your age? 22
You are already 22 years old, Bao !
Đủ tuổi đi bầu cử


“phép toán” if

In [67]:
A = (2, 3)   # tương ứng 2+3j
B = (5, 1)   # tương ứng 5+1j
X = A if A > B else B
print(X)

(5, 1)


### 2.3. Vòng lặp

Vòng lặp for

In [74]:
for d in range(10,20): # in các số từ 10 đến 19
  print(d)
print("-"*20)
for d in range(20,10,-1): # in các số từ 20 đến 11
  print(d)

10
11
12
13
14
15
16
17
18
19
--------------------
20
19
18
17
16
15
14
13
12
11


### 2.4. Hàm

Hàm tính tích 2 số

In [103]:
def tich(a, b):
    return a * b

Hàm có thể chỉ ra giá trị mặc định của tham số

In [104]:
def tich(a, b = 1):
  return a*b

In [105]:
print(tich(10, 20)) # 200
print(tich(10)) # 10
print(tich(a=5)) # 5
print(tich(b=6, a=5)) # 30

200
10
5
30


## 3. Chuỗi và danh sách

### 3.1. Kiểu dữ liệu tuần tự (sequential data type)

▪ Có 3 kiểu tuần tự thông dụng là list, tuple và range

▪ Có nhiều kiểu khác như string, bytes, bytearray,...hoặc các
lập trình viên có thể tự tạo kiểu riêng theo nhu cầu .

### 3.2. String (chuỗi)

#### Kiểu chuỗi

Phép nối chuỗi (+)

In [107]:
s = "Good" + " " + "Morning!"
print(s)

Good Morning!


Phép nhân bản (*)

In [109]:
s = "AB" * 3 # số nguyên
print(s)

ABABAB


Kiểm tra nội dung

In [110]:
s in '1ABABABCD' # True

True

#### Cắt chuỗi

In [113]:
s = '0123456789'
print(s[3:6])   # 345
print(s[3:])    # 3456789
print(s[:6])    # 012345
print(s[-7:-4]) # 345
print(s[-4:-7]) #
print(s[-4:-7:-1]) # 654
print(s[:len(s)])# 0123456789
print(s[:len(s)-1])# 012345678
print(s[:])# 0123456789
print(s[len(s)::-1]) # 9876543210
print(s[len(s)-1::-1])# 9876543210
print(s[len(s)-2::-1])# 876543210

345
3456789
012345
345

654
0123456789
012345678
0123456789
9876543210
9876543210
876543210


#### Định dạng chuỗi

- Nếu đánh dấu %s: thay thế bằng tham số dạng chuỗi
- Nếu đánh dấu %d: thay thế bằng tham số dạng nguyên
- Nếu đánh dấu %f: thay thế bằng tham số dạng thực

In [118]:
"Chao %s, gio la %d gio" % ('txnam', 10)
print("Chao %s, gio la %d gio" % ('txnam', 10))
"Can bac 2 cua 2 = %f" % (2**0.5)
print("Can bac 2 cua 2 = %f" % (2**0.5))
"Can bac 2 cua 2 = %10.3f" % (2**0.5)
print("Can bac 2 cua 2 = %10.3f" % (2**0.5))
"Can bac 2 cua 2 = %10f" % (2**0.5)
print("Can bac 2 cua 2 = %10f" % (2**0.5))
"Can bac 2 cua 2 = %.7f" % (2**0.5)
print("Can bac 2 cua 2 = %.7f" % (2**0.5))


Chao txnam, gio la 10 gio
Can bac 2 cua 2 = 1.414214
Can bac 2 cua 2 =      1.414
Can bac 2 cua 2 =   1.414214
Can bac 2 cua 2 = 1.4142136


Python cho phép định dạng chuỗi ở dạng f-string

In [123]:
myname = 'DHNTT'
s = f'This is {myname}.' # 'This is DHNTT.'
w = f'{s} {myname}' # 'This is DHNTT. DHNTT '
z = f'{{s}} {s}' # '{s} This is DHNTT.‘
print(s)
print(w)
print(z)

This is DHNTT.
This is DHNTT. DHNTT
{s} This is DHNTT.


Mạnh mẽ nhất là định dạng bằng format

In [124]:
# điền lần lượt từng giá trị vào giữa cặp ngoặc nhọn
'a: {}, b: {}, c: {}'.format(1, 2, 3)
# điền nhưng không lần lượt
'a: {1}, b: {2}, c: {0}'.format('one', 'two', 'three')
'two same values: {0}, {0}'.format(1, 2)
# điền và chỉ định từng giá trị
'1: {one}, 2: {two}'.format(one=111, two=222)

'1: 111, 2: 222'

Định dạng bằng format cho phép căn lề phong phú

In [128]:
# căn giữa: '   aaaa   '
print('{:^10}'.format('aaaa'))
# căn lề trái: 'aaaa      '
print('{:<10}'.format('aaaa'))
# căn lề phải: '      aaaa'
print('{:>10}'.format('aaaa'))
# căn lề phải, thay khoảng trắng bằng -: '------aaaa'
print('{:->10}'.format('aaaa'))
# căn lề trái, thay khoảng trắng bằng *: 'aaaa******'
print('{:*<10}'.format('aaaa'))
# căn giữa, thay khoảng trắng bằng +: '+++aaaa+++'
print('{:+^10}'.format('aaaa'))

   aaaa   
aaaa      
      aaaa
------aaaa
aaaa******
+++aaaa+++


#### Các phương thức của chuỗi

Tách chuỗi

In [135]:
input("Test: ").split(',')

Test: ăn, cơm , chưa


['ăn', ' cơm ', ' chưa']

Các phương thức khác

In [136]:
'-'.join(('1', '2', '3'))

'1-2-3'

### 3.3. List (danh sách)

#### Giới thiệu và khai báo

In [138]:
print([1, 2, 3, 4, 5])  # list 5 số nguyên
print(['a', 'b', 'c', 'd'])  # list 4 chuỗi
print([[1, 2], [3, 4]]) # list 2 list con
print([1, 'one', [2, 'two']])  # list hỗn hợp
print([]) # list rỗng


[1, 2, 3, 4, 5]
['a', 'b', 'c', 'd']
[[1, 2], [3, 4]]
[1, 'one', [2, 'two']]
[]


#### Khởi tạo list

Tạo list bằng constructor

In [140]:
l1 = list([1, 2, 3, 4]) # list 4 số nguyên
l2 = list('abc') # list 3 chuỗi con
l3 = list() # list rỗng
print(l1)
print(l2)
print(l3)

[1, 2, 3, 4]
['a', 'b', 'c']
[]


Tạo list bằng list comprehension

In [141]:
# list 1000 số nguyên từ 0 đến 999
X = [n for n in range(1000)]
# list gồm 10 list con là các cặp [x, x2]
# với x chạy từ 0 đến 9
Y = [[x, x*x] for x in range(10)]
print(X)
print(Y)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

#### Phép toán, chỉ mục và cắt

Điểm khác biệt là nội dung của list có thể thay đổi

In [142]:
l1 = list([1, 2, 3, 4])
l1[-1] = list('abc')
print(l1)
# [1, 2, 3, ['a', 'b', 'c']]

[1, 2, 3, ['a', 'b', 'c']]


#### Các phương thức của list

In [144]:
x = "Nguyen Van An".split()
x.sort(key=str.lower)
print(x)

['An', 'Nguyen', 'Van']


### 3.4. Tuple (hàng)

#### Tuple là một dạng readonly list

In [146]:
print(1, 2, 3, 4, 5) # tuple 5 số nguyên
print('a', 'b', 'c', 'd') # tuple 4 chuỗi
print(1, 'one', [2, 'two']) # tuple hỗ hợp
print(1,) # tuple 1 phần tử
print() # tuple rỗng

1 2 3 4 5
a b c d
1 one [2, 'two']
1



## 4. Tập hợp

### 4.1. Set (tập hợp) và Frozenset (tập hợp tĩnh)

#### Giới thiệu và khởi tạo

Khai báo trực tiếp bằng cách liệt kê các phần tử con đặt
trong cặp ngoặc nhọn { }, ngăn cách bởi phẩy.

In [147]:
basket = {'apple','orange','apple','pear'}
print(basket)
#{'orange','pear','apple'} : xóa trùng nhau

{'apple', 'pear', 'orange'}


In [148]:
a = {5,2,3,1,4}
print("a=", a) #a = {1, 2, 3, 4, 5}

a= {1, 2, 3, 4, 5}


Tạo set bằng constructor

In [153]:
s1 = set([1, 2, 3, 4]) # {1, 2, 3, 4}
s2 = set((1, 1, 1)) # {1}
s3 = s1 - s2 # {2, 3, 4}
s4 = set(range(1,100)) # {1, 2, 3,..., 98, 99}
print(s1)
print(s2)
print(s3)
print(s4)

{1, 2, 3, 4}
{1}
{2, 3, 4}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99}


#### Khởi tạo Set

Tạo set bằng set comprehension

In [155]:
# a = {'r', 'd'}
a = {x for x in 'abracadabra' if x not in 'abc'}
print(a)

{'r', 'd'}


Set không thể chứa những đối tượng mutable (có thể bị
thay đổi), mặc dù chính set lại có thể thay đổi

In [160]:
#a = set(([1,2],[2,3])) # lỗi list
a = set(((1,2),(2,3))) # {(1, 2), (2, 3)}
print(a)
a.add("abc") # {(1, 2), "abc", (2, 3)}
print(a)


{(2, 3), (1, 2)}
{(2, 3), 'abc', (1, 2)}


Frozenset giống set, nhưng không thể bị thay đổi

In [164]:
b = frozenset(((1,2),(2,3))) # {(1,2), (2,3)}
print(b)
#b.add("abc") # lỗi


frozenset({(2, 3), (1, 2)})


#### Set

Set Hỗn hợp

In [166]:
my_set = {8.0, "Sinh viên", (1, 2, 3)}
print("ketqua_Set=",my_set)
#Output: ketqua_Set= {'Sinh viên', 8.0, (1, 2, 3)}

ketqua_Set= {8.0, (1, 2, 3), 'Sinh viên'}


In [168]:
# Khởi tạo my_set
my_set = {1,3}
my_set.add(2) #thêm
my_set.update([2,3,4]) # Cập nhật
my_set.update([4,5], {1,6,8}) # Cập nhật set
print(my_set)
# Output: {1, 2, 3, 4, 5, 6, 8}

{1, 2, 3, 4, 5, 6, 8}


#### Các phép toán trên set

In [171]:
a = set('abracadabra') # {'d', 'r', 'c', 'b', 'a'}
b = set('alacazam') # {'z', 'c', 'm', 'l', 'a'}
# Phép Hiệu: thuộc a nhưng không thuộc b

print(a - b) # {'r', 'd', 'b'}

# Phép Hợp: thuộc a hoặc b
# {'a', 'c', 'r', 'd', 'b', 'm', 'z', 'l'}

print(a | b)

# Phép Giao: thuộc cả a và b

print(a & b) # {'a', 'c'}

# Phép Xor: thuộc hoặc a, hoặc b nhưng không phải cả 2
# {'r', 'd', 'b', 'm', 'z', 'l'}
print(a ^ b)

{'b', 'r', 'd'}
{'d', 'z', 'm', 'b', 'a', 'l', 'c', 'r'}
{'c', 'a'}
{'l', 'r', 'z', 'm', 'd', 'b'}


#### Các phương thức của set

In [172]:
num = {1,3,5,6,8,20,7,8,29,33}
print("Số lớn nhất là :", max(num))
#Số lớn nhất là : 33

Số lớn nhất là : 33


Vòng lặp for của set()

In [174]:
setFruits = {'lemon','orange','apple','pear'}
for x in setFruits:
  print(x)

apple
lemon
pear
orange


In [176]:
for letter in set("chivuong"):
  print(letter)

n
i
g
v
u
h
o
c


### 4.2. Dictionary (từ điển)

Từ điển có thể khai báo theo cú pháp của set

In [184]:
dict = {1:'one',2:'two',3:'three'}
print(dict[1]) #'one'
dict[4]='four'
print(dict)
#{1: 'one',2:'two',3:'three',4:'four'}

one
{1: 'one', 2: 'two', 3: 'three', 4: 'four'}


Chú ý: chỉ những loại dữ liệu immutable (không thể
thay đổi) mới có thể dùng làm key của từ điển

In [179]:
dict = {(1,2,3):"abc", 3.1415:"abc"}
print(dict)
#dict = {[1,2,3]:"abc"} # lỗi

{(1, 2, 3): 'abc', 3.1415: 'abc'}


Dùng zip để ghép 2 list thành từ điển

In [183]:
l1 = ["a","b","c"]
l2 = [1,2,3]
c = zip(l1, l2)
for i in c:
  print(i)

#('a', 1)
#('b', 2)
#('c', 3)

('a', 1)
('b', 2)
('c', 3)


Tạo mới từ điển

In [186]:
# tạo một dict với key là các số nguyên
Dict = {1: 'Nguyen', 2: 'Van', 3: 'An'}
print(Dict)
# {1: ‘Nguyen’, 2: ‘Van’, 3: ‘an’}

{1: 'Nguyen', 2: 'Van', 3: 'An'}


In [187]:
# tạo một dict với key hỗn hợp
Dict = {'Name': 'dict', 1: [1, 2, 3, 4]}
print(Dict)
# {'Name': 'dict', 1: [1, 2, 3, 4]}

{'Name': 'dict', 1: [1, 2, 3, 4]}


Thêm các giá trị vào từ điển

In [190]:
# tạo một từ điển
Dict = {}
# thêm các giá trị
Dict[0] = 'Xin chao'
Dict[1] = 'lop hoc Khoa học du lieu'
print(Dict)
# {0: ' Xin chao ', 1: ' Khoa học du lieu'}

{0: 'Xin chao', 1: 'lop hoc Khoa học du lieu'}


Truy cập giá trị của từ điển

In [192]:
# tạo một dict mới
Dict = {1: 'Lớp', 2: 'Khoa học', 3: 'Dữ liệu'}

In [193]:
# truy cập theo cách thông thường
print(Dict[1])
# Lớp

Lớp


In [194]:
# truy cập bằng phương thức get()
print(Dict.get(3))
# Dữ liệu

Dữ liệu


Chuyển từ điển thành chuỗi: str()

In [201]:
Dict = {'Ten':'An','Tuoi':20};
print("Chuỗi tương đương là : %s" % Dict)
#Chuỗi tương đương là : {'Ten': ‘An', 'Tuoi': 20}

Chuỗi tương đương là : {'Ten': 'An', 'Tuoi': 20}


Cập nhật 1 giá trị của từ điển: update()

In [203]:
Dict = {'Cúc':18, 'Lan':19, 'Hồng':20, 'Mai':27}
Dict.update({'Lan':21}) #cập nhật tuổi cho Lan
Dict.update({'Đào':25}) #thêm một phần tử mới là Đào
print(Dict)
#{'Cúc':18,'Lan':21,'Hồng':20,'Mai':27,'Đào':25}

{'Cúc': 18, 'Lan': 21, 'Hồng': 20, 'Mai': 27, 'Đào': 25}


### 4.3. Module và Package

Package

In [206]:
import numpy
#A = array([1, 2, 3]) # lỗi
A = numpy.array([1, 2, 3]) # ok
print(A)
import numpy as np
B = np.array([1, 2, 3]) # ok
print(B)
from numpy import array
C = array([1, 2, 3]) # ok
print(C)

[1 2 3]
[1 2 3]
[1 2 3]


# Thư viện NumPy

## 1. Một số gói python cho Data Science

## 2. Giới thiệu về NumPy

## 3. Khởi tạo mảng và chỉ số

Tạo mảng và truy cập

In [208]:
a = np.array([1, 2, 3]) # tạo mảng 1 chiều
print(type(a)) # in "<class 'numpy.ndarray'>"
print(a.shape) # in "(3,)"
print(a[0], a[1], a[2]) # in "1 2 3"
a[0] = 5
print(a) # in "[5, 2, 3]"
b = np.array([[1, 2, 3],[4, 5, 6]]) # tạo mảng 2 chiều
print(b.shape) # in "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) # in "1 2 4"
print(np.diag([1, 3, 4])) # in ra cái gì?

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4
[[1 0 0]
 [0 3 0]
 [0 0 4]]


Nhiều cách khởi tạo phong phú

In [217]:
import numpy as np

x = np.arange(3.0) # mảng [0. 1. 2.]
a = np.zeros((2, 2)) # mảng 2x2 toàn số 0
b = np.ones((1, 2)) # mảng 1x2 toàn số 1
c = np.full((3, 2, 2), 9) # mảng 3x2x2 toàn số 9
d = np.eye(2) # ma trận đơn vị 2x2
e = np.random.random((3, 2)) # mảng 3x2 ngẫu nhiên [0,1)
# mảng 2x3 điền các số từ 1 đến 6, kiểu số nguyên 32 bit
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(a)
print(b)
print(c)
print(d)
print(e)
print(x.ndim, x.size)
print(x.shape) # in "(2, 3)"
print(x.dtype) # in "dtype('int32')"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[[9 9]
  [9 9]]

 [[9 9]
  [9 9]]

 [[9 9]
  [9 9]]]
[[1. 0.]
 [0. 1.]]
[[0.10656085 0.55845567]
 [0.95948134 0.13270462]
 [0.39847505 0.86869739]]
2 6
(2, 3)
int32


Truy cập theo chỉ số (slicing)

In [219]:
import numpy as np
# mảng 3x4
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# mảng 2x2 trích xuất từ a, dòng 0+1, cột 1+2
b = a[:2, 1:3]
# chú ý: mảng của numpy tham chiếu chứ không copy dữ liệu
print(a[0, 1]) # in "2"
b[0, 0] = 77 # b[0, 0] cũng là a[0, 1]
print(a[0, 1]) # in "77"
print(a)
print(b)

2
77
[[ 1 77  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[77  3]
 [ 6  7]]


Cẩn thận với slicing

In [220]:
row_r1 = a[1, :] # mảng 1 chiều độ dài 4
row_r2 = a[1:2, :] # mảng 2 chiều 1x4
print(row_r1, row_r1.shape) # in ra "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # in ra "[[5 6 7 8]] (1, 4)"
col_r1 = a[:, 1] # mảng 1 chiều độ dài 3
col_r2 = a[:, 1:2] # mảng 2 chiều 3x1
print(col_r1, col_r1.shape) # in ra "[ 2 6 10] (3,)"
print(col_r2, col_r2.shape) # in ra "[[ 2]

# [ 6]
# [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


## 4. Các phép toán trên mảng

NumPy có nhiều phép toán về mảng

In [222]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x + y) # print(np.add(x, y)), xử lý khác list
print(x - y) # print(np.subtract(x, y))
print(x * y) # print(np.multiply(x, y))
print(x / y) # print(np.divide(x, y))
print(np.sqrt(x)) # khai căn tất cả các phần tử
print(2**x) # tính 2 mũ các phần tử trong x
# chú ý: phép nhân/chia thực hiện theo cặp phần tử của x và y

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[ 2.  4.]
 [ 8. 16.]]


Nhân ma trận (dot) và nghịch đảo

In [223]:
import numpy as np

x = np.array([[1, 2],[3, 4]])
y = np.array([[5, 6],[7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])
print(v.dot(w)) # tương tự print(np.dot(v, w))
print(x.dot(v)) # tương tự print(np.dot(x, v))
print(x.dot(y)) # tương tự print(np.dot(x, y))
print(np.linalg.inv(x)) # tính và in nghịch đảo của x

219
[29 67]
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Ma trận chuyển vị

In [224]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
print(x) # in ra "[[1 2]
# [3 4]]"
print(x.T) # in ra "[[1 3]
# [2 4]]"
# chú ý: mảng 1 chiều không có chuyển vị
y = np.array([1, 2, 3])
print(y) # in ra "[1 2 3]"
print(y.T) # in ra "[1 2 3]"
z = np.array([[1, 2, 3]])
print(z.T) # đoán xem in ra cái gì?

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
[[1]
 [2]
 [3]]


## 5. Một số thao tác thông dụng

Đọc dữ liệu từ file

In [227]:
from io import StringIO
import numpy as np
c = StringIO("0 1\n2 3")
x = np.loadtxt(c) # array([[ 0., 1.],
# [ 2., 3.]])
d = StringIO("M 21 72\nF 35 58")
y = np.loadtxt(
    d,
    dtype={'names': ('gender','age','weight'),
           'formats': ('S1', 'i4', 'f4')}
)
print(y) # [('M', 21, 72.0), ('F', 35, 58.0)]

[(b'M', 21, 72.) (b'F', 35, 58.)]


Cơ chế broadcasting

In [230]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11,
12]])
v = np.array([1, 0, 1])
y = x + v
print(y) # in ra "[[ 2 2 4]
          # [ 5 5 7]
          # [ 8 8 10]
          # [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Tính tổng theo các trục

In [231]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x)) # tính tổng toàn bộ x, in "10“
print(np.sum(x, axis=0)) # tính tổng mỗi cột, in "[4 6]“
print(np.sum(x, axis=1)) # tính tổng mỗi hàng, in "[3 7]"

10
[4 6]
[3 7]


Trích xuất dữ liệu theo dãy

In [232]:
import numpy as np
a = np.array([[1,2], [3, 4], [5, 6]])
# Prints "[1 4 5]"
print(a[[0, 1, 2], [0, 1, 0]])
# Prints "[1 4 5]"
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))
# Prints "[2 2]"
print(a[[0, 0], [1, 1]])
# Prints "[2 2]"
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 4 5]
[2 2]
[2 2]


Lọc phần tử theo chỉ số

In [233]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b = np.array([0, 2, 0, 1]) # b là mảng các chỉ số
print(a[np.arange(4), b]) # in ra "[1 6 7 11]"
# cộng tất cả các phần tử được lọc thêm 10
a[np.arange(4), b] += 10
print(a) # in ra "array([[11, 2, 3],

# [ 4, 5, 16],
# [17, 8, 9],
# [10, 21, 12]])

[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## Khởi tạo mảng và chỉ số

# Thư viện matplotlib

## 1. Giới thiệu và cài đặt matplotlib

## 2. Vẽ biểu đồ đơn giản

## 3. Một số loại biểu đồ thông dụng trong matplotlib

### 1. Biểu đồ dạBiểu đồ dạng cột (bar plot)

### 2. Biểu đồ bánh (pie chart)

### 3. Biểu đồ bánh (pie chart)

## 4. Một số chức năng hữu ích

# Thư viện Panda

## 1. Giới thiệu và cài đặt pandas

## 2. Cấu trúc dữ liệu trong pandas

## 3. Làm việc với series

## 4. Làm việc với dataframe

## 5. Bài tập

## 6. Hướng dẫn bài tập buổi trước

## 7. Làm việc với panel

## 8. Chọn và nhóm phần tử

## 9. Sử dụng pandas trong bài toán thực tế

# Thư viện scikit-learn

## 1. Mối quan hệ giữa Khoa học Dữ liệu và Học máy

## 2. Một số loại bài toán học máy

## 3. Thư viện học máy scikit-learn

# **Kết thúc**